### ISSUE TITLE
Error:  'ConcurrentResolve' is only available in macOS 12 or newer

### ISSUE THREAD

**Issue by cshadek** [d-exclaimation/pioneer#126] opened 2023-02-14 18:11 UTC
**Describe the bug**
I think this may be caused by a recent change to Graphiti in version 1.7.0.

The error is:  `ConcurrentResolve' is only available in macOS 12 or newer`

I think what happened is that Graphiti's `ConcurrentResolve` now requires macOS 12, but pioneer still supports older OS versions.

**Comment by d-exclaimation** [comment] 2023-02-14 21:36
> I think what happened is that Graphiti's ConcurrentResolve now requires macOS 12, but pioneer still supports older OS versions.

Actually, it should be the other way around. Recently, a PR was made to make Pioneer supports older macOS version by bumping the requirement from Swift 5.5 (macOS v12 or higher) to Swift 5.5.1 (macOS v10.15 or higher). 

Main branch of Graphiti still shows that `ConcurrentResolve` is available from macOS v10.15:
- https://github.com/GraphQLSwift/Graphiti/blob/14f378c8b2b2461b77449f215236d4be2f08402f/Sources/Graphiti/Field/Resolve/ConcurrentResolve.swift#L5

I'll double check this using the latest version of Graphiti. Not sure why 1.7.0 would break this since it only adds a feature for GraphQL federation.

**Comment by d-exclaimation** [comment] 2023-02-14 21:39
@cshadek  Also can you share your `Package.swift`'s `platforms` properties, specifically the macOS version your server is restricted to?

**Comment by d-exclaimation** [comment] 2023-02-14 22:17
I couldn't reproduce the issue here, I was able to break other packages but not Graphiti.

**Comment by d-exclaimation** [comment] 2023-03-15 22:32
I am closing this issue as there's no update on it. Feel free to reopen the issue if the problem still occurs

**Closed by d-exclaimation** 2023-03-15 22:32 UTC
Labels: bug
